version: 1.0.0-nightly-{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
max_jobs: 1
image: Visual Studio 2017
clone_depth: 1
build_script:
- ps: |-
    # Version number
    $BUILD_NUMBER = [int]$Env:APPVEYOR_BUILD_NUMBER
    $BUILD_SUFFIX = "nightly"

    # Branch
    $BRANCH = "$Env:APPVEYOR_REPO_BRANCH"
    $Env:DOCFX_SOURCE_BRANCH_NAME = "$BRANCH"

    # Output directory
    $Env:ARTIFACT_DIR = ".\artifacts"
    $dir = New-Item -type directory $env:ARTIFACT_DIR
    $dir = $dir.FullName

    # Verbosity
    Write-Host "Build: $BUILD_NUMBER / Branch: $BRANCH"
    Write-Host "Artifacts will be placed in: $dir"

    # Build
    Write-Host "Building from PR ($Env:APPVEYOR_PULL_REQUEST_NUMBER); skipping docs build"
    & .\build\rebuild-all.ps1 -ArtifactLocation "$dir" -Configuration "Release" -VersionSuffix "$BUILD_SUFFIX" -BuildNumber $BUILD_NUMBER 
artifacts:
- path: artifacts\*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/emzi0767-nightly/api/v2/package
  api_key:
    secure: k0YIk0KMqE3V0avtHJSx6iA2ay3Pw1lwJf7kGLqrZQ/5dLFvv2oNzyG1572hf/VT
  symbol_server: https://www.myget.org/F/emzi0767-nightly/symbols/api/v2/package
notifications:
- provider: Slack
  incoming_webhook: 
    secure: z4bpoeWztbUGxF4yxdUMUjU9XFR2JNtrCdCmiG7Ri7yYb1pprTQgAU22LPGhbPxegYMPL5/YZa+PhuxQuCbN9pY7VKlszvnoBCml8UsyV+qv9PasFgsk2VQikylsuX3oynCcNrt9zNfRfpGJeDWOTA1QN0hu2OZTyuxuwOz3tES6woj8W5c8Wb4Ae6+sb+vE
  channel: gitfeed
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
